---
title: "Create Data Table"
author: "Chinyere Brown"
date: "12/12/2019"
output: html_document
---

```{r setup, include=TRUE}
library(tidyverse)
library(ggplot2)
library(lubridate)

testImport <- read_csv(file = "C:\\Users\\Valued User\\Documents\\CJ Class\\FinalProj\\voterMeckCo.csv")

voterMeck <- testImport

elecList <- c("10/08/2019",
              "09/10/2019",
              "05/14/2019",
              "11/06/2018",
              "05/08/2018",
              "11/07/2017",
              "09/12/2017",
              "11/08/2016",
              "03/15/2016",
              "11/03/2015",
              "10/06/2015",
              "09/15/2015",
              "11/04/2014",
              "05/06/2014",
              "11/05/2013",
              "10/08/2013",
              "09/10/2013",
              "11/06/2012",
              "07/17/2012",
              "05/08/2012")

eDate <- lapply(elecList, function(x) {
  as.Date(as.character(as.POSIXct(x, format = "%m/%d/%Y")))  
})

eDateMin25 <- lapply(eDate, function(x) {
  x-25
})  


dateSufx <- function(date) {
  eDate <- as.POSIXct(date, format = "%m/%d/%Y")
  suffix <- paste0(stringr::str_sub(eDate, 1, 4), stringr::str_sub(eDate, 6, 7), stringr::str_sub(eDate, 9, 10))
  }
# run function to create date suffixes for new variable names
elecSufx <- lapply(elecList, dateSufx)

# create blank list, use for loop to make list of new column names.
elecNames <- NULL
for (i in 1:length(elecList)) {
  elecNames[[i]] <- paste0("E", i, "_", elecSufx[[i]])
}

# Create List of election date column names
dateCols1 <- voterMeck[, grepl("date", names(voterMeck))]
dateCols2 <- voterMeck[, grepl("Date", names(voterMeck))]
dates <- c(c(names(dateCols1)), c(names(dateCols2)))

# Change class of date columns as appropriate:
voterMeck$registr_dt <- as.Date(as.character(voterMeck$registr_dt))
voterMeck[,dates] = apply(voterMeck[,dates], 2, function(x) as.POSIXct(x, format = "%m/%d/%Y"))

for (i in 1:20) {
  voterMeck <- mutate(voterMeck, elecNames[i] = 
                      ifelse(!is.na(dates[i]), 1,
                      ifelse(is.na(dates[i]) & registr_dt <= as.Date(eDateMin25[[1]]), 0, NA)))
}

#voterMeck <- mutate(voterMeck, E1_20191008 = 0)
voterMeck <- mutate(voterMeck, E1_20191008 = 
                      ifelse(!is.na(E1_date), 1,
                      ifelse(is.na(E1_date) & registr_dt <= as.Date(eDateMin25[[1]]), 0, NA)))
print(levels(as.factor(voterMeck$E1_20191008)))


#voterMeck <- mutate(voterMeck, E2_20190910 = 0)
voterMeck <- mutate(voterMeck, E2_20190910 = 
                      ifelse(!is.na(E2_Date), 1,
                      ifelse(is.na(E2_Date) & registr_dt <= as.Date(eDateMin25[[2]]), 0, NA)))
print(levels(as.factor(voterMeck$E2_20190910)))


#voterMeck <- mutate(voterMeck, E3_20190514 = 0)
voterMeck <- mutate(voterMeck, E3_20190514 = 
                      ifelse(!is.na(E3_Date), 1,
                      ifelse(is.na(E3_Date) & registr_dt <= as.Date(eDateMin25[[3]]), 0, NA)))
print(levels(as.factor(voterMeck$E3_20190514)))


voterMeck <- mutate(voterMeck, E4_20181106 = 
                      ifelse(!is.na(E4_Date), 1,
                      ifelse(is.na(E4_Date) & registr_dt <= as.Date(eDateMin25[[4]]), 0, NA)))
print(levels(as.factor(voterMeck$E4_20181106)))


voterMeck <- mutate(voterMeck, E5_20180508 = 
                      ifelse(!is.na(E5_Date), 1,
                      ifelse(is.na(E5_Date) & registr_dt <= as.Date(eDateMin25[[5]]), 0, NA)))
print(levels(as.factor(voterMeck$E5_20180508)))


voterMeck <- mutate(voterMeck, E6_20171107 = 
                      ifelse(!is.na(E6_Date), 1,
                      ifelse(is.na(E6_Date) & registr_dt <= as.Date(eDateMin25[[6]]), 0, NA)))
print(levels(as.factor(voterMeck$E6_20171107)))


voterMeck <- mutate(voterMeck, E7_20170912 = 
                      ifelse(!is.na(E7_Date), 1,
                      ifelse(is.na(E7_Date) & registr_dt <= as.Date(eDateMin25[[7]]), 0, NA)))
print(levels(as.factor(voterMeck$E7_20170912)))


voterMeck <- mutate(voterMeck, E8_20161108 = 
                      ifelse(!is.na(E8_Date), 1,
                      ifelse(is.na(E8_Date) & registr_dt <= as.Date(eDateMin25[[8]]), 0, NA)))
print(levels(as.factor(voterMeck$E8_20161108)))


voterMeck <- mutate(voterMeck, E9_20160315 = 
                      ifelse(!is.na(E9_Date), 1,
                      ifelse(is.na(E9_Date) & registr_dt <= as.Date(eDateMin25[[9]]), 0, NA)))
print(levels(as.factor(voterMeck$E9_20160315)))


voterMeck <- mutate(voterMeck, E10_20151103 = 
                      ifelse(!is.na(E10_Date), 1,
                      ifelse(is.na(E10_Date) & registr_dt <= as.Date(eDateMin25[[10]]), 0, NA)))
print(levels(as.factor(voterMeck$E10_20151103)))


voterMeck <- mutate(voterMeck, E11_20151006 = 
                      ifelse(!is.na(E11_Date), 1,
                      ifelse(is.na(E11_Date) & registr_dt <= as.Date(eDateMin25[[11]]), 0, NA)))
print(levels(as.factor(voterMeck$E11_20151006)))


voterMeck <- mutate(voterMeck, E12_20150915 = 
                      ifelse(!is.na(E12_Date), 1,
                      ifelse(is.na(E12_Date) & registr_dt <= as.Date(eDateMin25[[12]]), 0, NA)))
print(levels(as.factor(voterMeck$E12_20150915)))


voterMeck <- mutate(voterMeck, E13_20141104 = 
                      ifelse(!is.na(E13_Date), 1,
                      ifelse(is.na(E13_Date) & registr_dt <= as.Date(eDateMin25[[13]]), 0, NA)))
print(levels(as.factor(voterMeck$E13_20141104)))


voterMeck <- mutate(voterMeck, E14_20140506 = 
                      ifelse(!is.na(E14_Date), 1,
                      ifelse(is.na(E14_Date) & registr_dt <= as.Date(eDateMin25[[14]]), 0, NA)))
print(levels(as.factor(voterMeck$E14_20140506)))


voterMeck <- mutate(voterMeck, E15_2013110 = 
                      ifelse(!is.na(E15_Date), 1,
                      ifelse(is.na(E15_Date) & registr_dt <= as.Date(eDateMin25[[15]]), 0, NA)))
print(levels(as.factor(voterMeck$E15_2013110)))


voterMeck <- mutate(voterMeck, E16_20131008 = 
                      ifelse(!is.na(E16_Date), 1,
                      ifelse(is.na(E16_Date) & registr_dt <= as.Date(eDateMin25[[16]]), 0, NA)))
print(levels(as.factor(voterMeck$E16_20131008)))


voterMeck <- mutate(voterMeck, E17_20130910 = 
                      ifelse(!is.na(E17_Date), 1,
                      ifelse(is.na(E17_Date) & registr_dt <= as.Date(eDateMin25[[17]]), 0, NA)))
print(levels(as.factor(voterMeck$E17_20130910)))


voterMeck <- mutate(voterMeck, E18_20121106 = 
                      ifelse(!is.na(E18_Date), 1,
                      ifelse(is.na(E18_Date) & registr_dt <= as.Date(eDateMin25[[18]]), 0, NA)))
print(levels(as.factor(voterMeck$E18_20121106)))


voterMeck <- mutate(voterMeck, E19_20120717 = 
                      ifelse(!is.na(E19_Date), 1,
                      ifelse(is.na(E19_Date) & registr_dt <= as.Date(eDateMin25[[19]]), 0, NA)))
print(levels(as.factor(voterMeck$E19_20120717)))


voterMeck <- mutate(voterMeck, E20_20120508 = 
                      ifelse(!is.na(E20_Date), 1,
                      ifelse(is.na(E20_Date) & registr_dt <= as.Date(eDateMin25[[20]]), 0, NA)))
print(levels(as.factor(voterMeck$E20_20120508)))



eDate <- lapply(elecList, function(x) {
  as.Date(as.character(as.POSIXct(x, format = "%m/%d/%Y")))  
})
eDateMin25 <- lapply(eDate, function(x) {
  x-25
})  



filterTest1 <- voterMeck %>% filter(!is.na(E1_date))
filterTest2a <- voterMeck %>% filter(is.na(E1_date) & registr_dt > as.Date(eDateMin25[[1]]))
filterTest2b <- voterMeck %>% filter(is.na(E1_date) & registr_dt <= as.Date(eDateMin25[[1]]))

filter1 <- voterMeck %>% filter(E3_20190514==1)
filter2a <- voterMeck %>% filter(E3_20190514==0)
filter2b <- voterMeck %>% filter(is.na(E3_20190514))


methods <- table(voterMeck$E1_VotingMethod)


#if (voterMeck$registr_dt <= eDateMin25[[1]] & voterMeck$E1_VotingMethod != "O" & voterMeck$E1_VotingMethod != "U") {voterMeck$E1_20191008 = 0}

#unneccessary
#if (voterMeck$registr_dt = eDate[[1]] & (voterMeck$E1_VotingMethod = "O" | voterMeck$E1_VotingMethod = "U")) {E1_20191008 = 1}
#from ifelse part 2...